### ISSUE TITLE
Layout embedded nella vista

### ISSUE THREAD

**Issue by elia** [net2b/spree_gestpay#2]
@kennyadsl ho scoperto che la vista [secure_3d](https://github.com/net2b/spree_gestpay/blob/7107638bc3a4dd5f9aa4f9d3ac5201a2d0b9c2e1/app/views/spree/gestpay_iframe_callbacks/secure_3d.html.erb#L1-L23) include il layout completo, ma [il controller](https://github.com/net2b/spree_gestpay/blob/7107638bc3a4dd5f9aa4f9d3ac5201a2d0b9c2e1/app/controllers/spree/gestpay_iframe_callbacks_controller.rb#L9-L12) non fa nulla per evitare che il render venga fatto senza layout

io la renderei una vista normale, ma volevo chiederti se l'avevi fatto per qualche motivo…

**Comment by kennyadsl** [comment]
era stato fatto nella vecchia piattaforma perché si voleva evitare che gli utenti cliccassero qui e li e quindi si renderizzava il layout di default. Qui possiamo fare come ci pare. Intanto fixerò al più presto la gem in modo che renderizzi il layout di base.

**Comment by masterkain** [comment]
penso si possa chiudere, riaprire altrimenti se e' ancora cosa attuale
